# Generated by Django 4.2.2 on 2023-09-30 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('random_contacts_app', '0007_alter_contact_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='status',
            field=models.CharField(default='inactive', max_length=100),
        ),
    ]
