# Generated by Django 4.2.2 on 2023-09-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('random_contacts_app', '0008_myuser_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromPhone', models.CharField(max_length=255)),
                ('toPhone', models.CharField(max_length=255)),
                ('isActive', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='myuser',
            name='name',
            field=models.CharField(default='default', max_length=255),
        ),
    ]
