# Generated by Django 4.2.2 on 2023-09-30 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('random_contacts_app', '0009_connection_myuser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='fromStatus',
            field=models.CharField(default='accepting', max_length=255),
        ),
        migrations.AddField(
            model_name='connection',
            name='toStatus',
            field=models.CharField(default='accepting', max_length=255),
        ),
    ]
